# Generated by Django 4.2.1 on 2026-06-24 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dummy', max_length=255, verbose_name='Author Name')),
                ('publication_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publication Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Author Description')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Author Address')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nationality')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('webiste', models.URLField()),
                ('isActive', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
