# Generated by Django 5.2.12 on 2026-04-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='Dummy', max_length=255, verbose_name='Author Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='publication_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Publication Name'),
        ),
    ]
