# Generated by Django 4.2.1 on 2026-04-06 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category Name')),
                ('created_at', models.DateField(auto_now=True)),
                ('modified_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publication Name')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publication Address')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('webiste', models.URLField()),
                ('isActive', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Book Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='book/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_image')),
                ('edition', models.PositiveIntegerField()),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('page_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('demo_text', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=2)),
                ('isActive', models.BooleanField()),
                ('isPublished', models.BooleanField()),
                ('created_at', models.DateField(auto_now=True)),
                ('modified_at', models.DateField(auto_now_add=True)),
                ('author', models.ManyToManyField(to='author.author')),
                ('category', models.ManyToManyField(to='book.category')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.genre')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book.publication')),
            ],
        ),
    ]
